version: '3.9'

services:
  web:
    container_name: my-awesome-app-bmp
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules

  test:
    container_name: my-awesome-app-bpm-test
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    command: ["npm", "test"]