name: Github Actions

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  single-command:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - name: Run a single command
        run: echo Hello, out there!

  multi-line:
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line command
        run: 
          echo
          ls -a
          echo
          java -version
          echo
          git --version
          echo
          mvn --version
          gradle --version
          ant -version
          echo
          echo $ANDROID_SDK_ROOT
          echo
          echo $SELENIUM_JAR_PATH
          echo
          echo $RUNNER_WORKSPACE
          echo
          whoami
          echo
          df
          echo
          env -0 | sort-z | tr'\0''\n'

