name: Docker test Image CI

env:
  DATE_STAMP: $(date +%s)

on:
  pull_request:
    # type: is an option too
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2

    - name: build docker image
      run: docker build . --file Dockerfile --tag brycepayne/my-awesome-app-bmp:latest

    - name: run docker image
      run: docker run my-awesome-app-bmp npm run test

    - name: run docker compost files
      run: docker-compose -f "Dockerfile.dev" up -d --build test
      

