name: Build Prod Image & Deploy to Docker Hub

env:
  DATE_STAMP: $(date +%s)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Env Variables
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV

      - name: Builds the docker image
        run: docker build . --file Dockerfile --tag brycepayne/my-awesome-app-bmp:latest  

      - name: add "date-stamp" tag to the image
        run: docker image tag brycepayne/my-awesome-app-bmp:${{env.date-stamp}}

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: push the docker image to docker hub
        run: docker push --all-tags brycepayne/my-awesome-app-bmp

      