name: Docker test Image CI

env:
  DATE_STAMP: $(date +%s)

on:
  push:
    branches: [main]
  pull_request:
    # type: is an option too
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2

    - name: Env variables
      run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag brycepayne/my-awesome-app-bmp-dev:latest

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: push the docker image to docker hub
      run: docker push --all-tags brycepayne/my-awesome-app-bmp

