name: Docker test Image CI

on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Docker compose on Dev files
        run: docker-compose -f "docker-compose-dev.yml" up -d --build test